{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Forecasting"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import boto3\n",
    "import io\n",
    "import json\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from unidecode import unidecode\n",
    "from sklearn.ensemble import HistGradientBoostingRegressor\n",
    "from sklearn.experimental import enable_halving_search_cv\n",
    "from sklearn.linear_model import RidgeCV\n",
    "from sklearn.model_selection import train_test_split, TimeSeriesSplit\n",
    "from sklearn.multioutput import RegressorChain\n",
    "from sklearn.neural_network import MLPRegressor\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import HalvingGridSearchCV"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def make_steps(\n",
    "    df : pd.DataFrame, \n",
    "    y : str, \n",
    "    steps : int\n",
    "    ) -> pd.DataFrame:\n",
    "    \"\"\"\n",
    "    Get target feature steps ahead.\n",
    "\n",
    "    Parameters\n",
    "    ----------\n",
    "    df : pandas data frame\n",
    "        Data frame with target feature.\n",
    "    \n",
    "    y : str\n",
    "        Target feature name.\n",
    "    \n",
    "    steps : int\n",
    "        Steps to forecast.\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    df : pandas data frame\n",
    "        Data frame with target features.\n",
    "    \"\"\"\n",
    "\n",
    "    for i in range(steps):\n",
    "        df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
    "    return df\n",
    "\n",
    "\n",
    "# models\n",
    "rid = RegressorChain(\n",
    "    base_estimator=RidgeCV(\n",
    "        alphas=[0.001, 0.01, 0.1, 1, 10, 100, 1000],\n",
    "        cv=TimeSeriesSplit(n_splits=3, test_size=2000),\n",
    "    ),\n",
    "    random_state=123\n",
    ")\n",
    "\n",
    "gb = RegressorChain(\n",
    "    base_estimator=HalvingGridSearchCV(\n",
    "        estimator=HistGradientBoostingRegressor(random_state=123),\n",
    "        param_grid = {\n",
    "            'learning_rate': [0.01, 0.05, 0.1, 0.2],\n",
    "            'max_iter': [100, 500, 1000],\n",
    "            'max_depth': [None, 3, 5, 10],\n",
    "            'min_samples_leaf': [20, 50, 100],\n",
    "            'l2_regularization': [0, 0.01, 0.1, 1]\n",
    "        },\n",
    "        cv=TimeSeriesSplit(n_splits=3, test_size=2000),\n",
    "        aggressive_elimination=True,\n",
    "        scoring=\"neg_mean_squared_error\",\n",
    "        random_state=123,\n",
    "        n_jobs=-1\n",
    "    ),\n",
    "    random_state=123\n",
    ")\n",
    "\n",
    "mlp = RegressorChain(\n",
    "    base_estimator=HalvingGridSearchCV(\n",
    "        estimator=MLPRegressor(max_iter=5000, random_state=123),\n",
    "        param_grid = {\n",
    "            'hidden_layer_sizes': [(50,), (50, 50), (100,), (100, 100), (100, 75, 25)],\n",
    "            'activation': ['relu', 'logistic', 'tanh', 'identity'],\n",
    "            'solver': ['adam', 'sgd', 'lbfgs'],\n",
    "            'alpha': [0.0001, 0.001, 0.01, 0.1],\n",
    "            'learning_rate': ['constant', 'invscaling', 'adaptive'],\n",
    "            'learning_rate_init': [0.001, 0.01, 0.1]\n",
    "        },\n",
    "        cv=TimeSeriesSplit(n_splits=3, test_size=2000),\n",
    "        aggressive_elimination=True,\n",
    "        scoring=\"neg_mean_squared_error\",\n",
    "        random_state=123,\n",
    "        n_jobs=-1\n",
    "    ),\n",
    "    random_state=123\n",
    ")\n",
    "\n",
    "models = {\n",
    "    # \"rid\": rid,\n",
    "    \"gb\": gb,\n",
    "    # \"mlp\": mlp,\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# AWS credentials to read files on S3 bucket\n",
    "f = open('../credentials.json')\n",
    "credentials = json.load(f)\n",
    "\n",
    "s3_client = boto3.client(\n",
    "    \"s3\",\n",
    "    aws_access_key_id=credentials[\"Access key ID\"],\n",
    "    aws_secret_access_key=credentials[\"Secret access key\"]\n",
    "    )\n",
    "\n",
    "s3_resource = boto3.resource(\n",
    "    \"s3\",\n",
    "    aws_access_key_id=credentials[\"Access key ID\"],\n",
    "    aws_secret_access_key=credentials[\"Secret access key\"]\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['processed/',\n",
       " 'processed/anhembi.csv',\n",
       " 'processed/butanta.csv',\n",
       " 'processed/campo_limpo.csv',\n",
       " 'processed/capela_do_socorro.csv',\n",
       " 'processed/cge_clusters.csv',\n",
       " 'processed/cidade_ademar.csv',\n",
       " 'processed/cluster_A.csv',\n",
       " 'processed/cluster_B.csv',\n",
       " 'processed/cluster_C.csv',\n",
       " 'processed/cluster_D.csv',\n",
       " 'processed/freguesia_do_o.csv',\n",
       " 'processed/ipiranga.csv',\n",
       " 'processed/itaim_paulista.csv',\n",
       " 'processed/itaquera.csv',\n",
       " 'processed/jabaquara.csv',\n",
       " 'processed/lapa.csv',\n",
       " \"processed/m'boi_mirim.csv\",\n",
       " 'processed/maua.csv',\n",
       " 'processed/mooca.csv',\n",
       " 'processed/parelheiros.csv',\n",
       " 'processed/penha.csv',\n",
       " 'processed/perus.csv',\n",
       " 'processed/pinheiros.csv',\n",
       " 'processed/pirituba.csv',\n",
       " 'processed/riacho_grande.csv',\n",
       " 'processed/santana_do_parnaiba.csv',\n",
       " 'processed/santo_amaro.csv',\n",
       " 'processed/sao_mateus.csv',\n",
       " 'processed/sao_miguel_paulista.csv',\n",
       " 'processed/se.csv',\n",
       " 'processed/tremembe.csv',\n",
       " 'processed/tucuruvi.csv',\n",
       " 'processed/vila_formosa.csv',\n",
       " 'processed/vila_maria.csv',\n",
       " 'processed/vila_mariana.csv',\n",
       " 'processed/vila_prudente.csv']"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "prefix_objs = s3_resource.Bucket(\"cge\").objects.filter(Prefix=\"processed\")\n",
    "keys = [obj.key for obj in prefix_objs]\n",
    "keys"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_3697/1772440060.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_3697/1772440060.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_3697/1772440060.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_3697/1772440060.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_3697/1772440060.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_3697/1772440060.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n"
     ]
    }
   ],
   "source": [
    "# getting preprocessed data\n",
    "# prefix_objs = s3_resource.Bucket(\"cge\").objects.filter(Prefix=\"processed\")\n",
    "# keys = [obj.key for obj in prefix_objs]\n",
    "keys = [\n",
    "    'processed/cluster_A.csv',\n",
    "    # 'processed/cluster_B.csv',\n",
    "    # 'processed/cluster_C.csv',\n",
    "    # 'processed/cluster_D.csv',\n",
    "    # 'processed/parelheiros.csv'\n",
    "]\n",
    "\n",
    "for key in keys:\n",
    "    obj = s3_client.get_object(Bucket=\"cge\", Key=key)\n",
    "    df = pd.read_csv(io.BytesIO(obj[\"Body\"].read()))\n",
    "    df = df.reset_index(drop=True)\n",
    "    \n",
    "    df = df.dropna(axis=1, how=\"all\")\n",
    "    df = df.dropna()\n",
    "    \n",
    "    cluster = df.cluster.unique()[0]\n",
    "    ts = df[[\"timestamp\"]]\n",
    "    df = df.drop([\"timestamp\", \"cluster\", \"Unnamed: 0\"], axis=1)\n",
    "\n",
    "    # target\n",
    "    y = make_steps(df=df[[\"temperature\"]], y=\"temperature\", steps=6).drop(\"temperature\", axis=1)\n",
    "    y = y.dropna()\n",
    "\n",
    "    # predictors\n",
    "    X = df.drop([\"temperature\"], axis=1)\n",
    "    X = X.loc[y.index.min():y.index.max()]\n",
    "\n",
    "    # scaling data\n",
    "    scaler = StandardScaler()\n",
    "    scaler.fit(X)\n",
    "    X_standard = scaler.transform(X)\n",
    "\n",
    "    # train and test data split\n",
    "    test_size = 0.30\n",
    "    X_train_ref, X_test_ref, _, _ = train_test_split(X, y, test_size=0.30, shuffle=False)\n",
    "    X_train, X_test, y_train, y_test = train_test_split(X_standard, y, test_size=test_size, shuffle=False)\n",
    "\n",
    "    # model training\n",
    "    for model in models:\n",
    "        models[model].fit(X_train, y_train)\n",
    "        y_pred = pd.DataFrame(models[model].predict(X_test), index=X_test_ref.index, columns=y.columns)\n",
    "        ts = ts.loc[y_pred.index.min():y_pred.index.max()]\n",
    "        y_pred[\"timestamp\"] = ts.timestamp \n",
    "        y_pred[\"cluster\"] = cluster\n",
    "\n",
    "        # writing predictions to S3 bucket\n",
    "        cluster_ = unidecode(key.lower().replace(\" \", \"_\").replace(\"processed/\", \"\").replace(\".csv\", \"\"))\n",
    "        file_name = cluster_ + \"_\" + model\n",
    "        buffer = io.StringIO()\n",
    "        y_pred.to_csv(buffer)\n",
    "        s3_resource.Object(\"cge\", f\"output_teste_2/{file_name}.csv\").put(Body=buffer.getvalue())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/tmp/ipykernel_4952/3261607407.py:27: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  df[f\"{y}_step_{i+1}\"] = df[y].shift(-i+1)\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/utils/extmath.py:193: RuntimeWarning: invalid value encountered in matmul\n",
      "  ret = a @ b\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n",
      "/home/ubuntu/ml-uhi/venv/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.\n",
      "  warnings.warn(\n"
     ]
    }
   ],
   "source": [
    "# # getting preprocessed data\n",
    "# # prefix_objs = s3_resource.Bucket(\"cge\").objects.filter(Prefix=\"processed\")\n",
    "# # keys = [obj.key for obj in prefix_objs]\n",
    "# keys = [\n",
    "#     'processed/cluster_A.csv',\n",
    "#     'processed/cluster_B.csv',\n",
    "#     'processed/cluster_C.csv',\n",
    "#     'processed/cluster_D.csv'\n",
    "# ]\n",
    "\n",
    "# for key in keys:\n",
    "#     obj = s3_client.get_object(Bucket=\"cge\", Key=key)\n",
    "#     df = pd.read_csv(io.BytesIO(obj[\"Body\"].read()))\n",
    "#     df = df.reset_index(drop=True)\n",
    "    \n",
    "#     df = df.dropna(axis=1, how=\"all\")\n",
    "#     df = df.dropna()\n",
    "    \n",
    "#     cluster = df.cluster.unique()[0]\n",
    "#     ts = df[[\"timestamp\"]]\n",
    "#     df = df.drop([\"timestamp\", \"cluster\", \"Unnamed: 0\"], axis=1)\n",
    "\n",
    "#     # target\n",
    "#     y = make_steps(df=df[[\"temperature\"]], y=\"temperature\", steps=6).drop(\"temperature\", axis=1)\n",
    "#     y = y.dropna()\n",
    "\n",
    "#     # predictors\n",
    "#     X = df.drop([\"temperature\"], axis=1)\n",
    "#     X = X.loc[y.index.min():y.index.max()]\n",
    "\n",
    "#     # scaling data\n",
    "#     scaler = StandardScaler()\n",
    "#     scaler.fit(X)\n",
    "#     X_standard = scaler.transform(X)\n",
    "\n",
    "#     # train and test data split\n",
    "#     test_size = 0.30\n",
    "#     X_train_ref, X_test_ref, _, _ = train_test_split(X, y, test_size=0.30, shuffle=False)\n",
    "#     X_train, X_test, y_train, y_test = train_test_split(X_standard, y, test_size=test_size, shuffle=False)\n",
    "\n",
    "#     # model training\n",
    "#     for model in models:\n",
    "#         models[model].fit(X_train, y_train)\n",
    "#         y_pred = pd.DataFrame(models[model].predict(X_test), index=X_test_ref.index, columns=y.columns)\n",
    "#         ts = ts.loc[y_pred.index.min():y_pred.index.max()]\n",
    "#         y_pred[\"timestamp\"] = ts.timestamp \n",
    "#         y_pred[\"cluster\"] = cluster\n",
    "\n",
    "#         # writing predictions to S3 bucket\n",
    "#         cluster_ = unidecode(key.lower().replace(\" \", \"_\").replace(\"processed/\", \"\").replace(\".csv\", \"\"))\n",
    "#         file_name = cluster_ + \"_\" + model\n",
    "#         buffer = io.StringIO()\n",
    "#         y_pred.to_csv(buffer)\n",
    "#         s3_resource.Object(\"cge\", f\"output/{file_name}.csv\").put(Body=buffer.getvalue())\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.6 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.6"
  },
  "vscode": {
   "interpreter": {
    "hash": "31f2aee4e71d21fbe5cf8b01ff0e069b9275f58929596ceb00d14d90e3e16cd6"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
